# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# Copy the Everything server source from the repository
COPY src/everything /app

# Copy the tsconfig file from the repo root (if needed for build)
COPY tsconfig.json /tsconfig.json

WORKDIR /app

# Install dependencies and build the project
RUN --mount=type=cache,target=/root/.npm npm install

# Assume that the build step transpiles TypeScript to JavaScript in /app/dist
# If a separate build command is required, add it here. For now, we assume npm install triggers a build

FROM node:22-alpine AS release

WORKDIR /app

# Copy built files and necessary artifacts from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

ENV NODE_ENV=production

RUN npm ci --ignore-scripts --omit-dev

CMD ["node", "dist/index.js"]
